### ISSUE TITLE
Extract application name from application manifests instead of from file names

### ISSUE THREAD

**Issue by hencrice** [aws/amazon-ecs-cli-v2#242] opened 2019-10-28 18:32 UTC
For now in #233, we extract the names of applications in a workspace by using the names of the app manifests. A more appropriate way would be to parse them out from the content app manifests.

**Comment by kohidave** [comment] 2019-11-09 01:07
The problem is that we'd have to load all the files in that directory, which is why we went with the filename approach.

**Comment by efekarakus** [comment] 2020-01-09 21:41
Resolving this issue. We can consider it if a user complains about it, seems to be minor enough

**Closed by efekarakus** 2020-01-09 21:41 UTC
Labels: enhancement
